#
# See also:
# - https://dev.to/arnu515/create-a-pypi-pip-package-test-it-and-publish-it-using-github-actions-part-2-1o83
# - https://docs.github.com/en/actions/guides/building-and-testing-python
# - https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository
# - https://github.com/pypa/sampleproject
# - https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
#

name: Upload to TestPyPI

# Controls when the action will run.
on:
  # Triggers the workflow on push to the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build, test and upload to TestPyPI

    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up python3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Creates venv upgrades pip, installs dependencies, etc. exactly as we do for development.
      - name: setup
        run: |
        ./wrapper.sh
        ./expand.sh --version

      - name: test
        run: |
          ./tox.sh

    - name: publish
      run: |
        python3 setup.py sdist bdist_wheel
        python3 -m twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        TWINE_REPOSITORY: testpypi
